### ISSUE TITLE
Chaincode substracc not found using docker start.py

### ISSUE THREAD

**Issue by IcyLiGit** [SubstraFoundation/hlf-k8s#85]
Hi, how can I solve this problem?
I set up my environment using docker. However, when I run the python3 start.py, I got the following errors: 
----------------------------------------------------------------------------------------

Loading configuration
Loaded configuration: /substra/data/orgs/chu-nantes/configtx.yaml
[common.tools.configtxgen.encoder] NewConsortiumOrgGroup
WARN Default policy emission is deprecated, please include policy specifications for the orderer org group chu-nantes in configtx.yaml
/substra/conf/config/conf-chu-nantes.json
Will getChannelConfigBlockWithOrderer
got ChannelConfigBlockWithOrderer
signAndPushSystemUpdateProposal
Generating channel configuration transaction at /substra/data/channel/substrachannel.tx
....
channel creation:  True
Wait For Peers to join channel
Join channel substrachannel with peers ['peer1-chu-nantes', 'peer2-chu-nantes'] ...
fail to get genesis block
Will retry to make peers join channel
fail to get genesis block
Will retry to make peers join channel
Peers ['peer1-chu-nantes', 'peer2-chu-nantes'] successfully joined channel substrachannel
Installing chaincode on ['peer1-chu-nantes', 'peer2-chu-nantes'] ...
policy:  OR('chu-nantesMSP.member')
Instantiated chaincode with policy: {'identities': [{'role': {'name': 'member', 'mspId': 'chu-nantesMSP'}}], 'policy': {'1-of': [{'signed-by': 0}]}} and result: "timeout expired while starting chaincode substracc:1.0 for transaction"
Try to query chaincode from peer ['peer1-chu-nantes', 'peer2-chu-nantes'] on org chu-nantes
Traceback (most recent call last):
  File "/scripts/run.py", line 135, in <module>
    add_org()
  File "/scripts/run.py", line 116, in add_org
    if client.queryChaincodeFromPeers() == '[]':
  File "/scripts/utils/run_utils.py", line 283, in queryChaincodeFromPeers
    cc_name=self.chaincode_name,
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/hfc/fabric/client.py", line 1662, in chaincode_query
    raise Exception(res)
Exception: [response {
  status: 500
  message: "make sure the chaincode substracc has been successfully instantiated and try again: chaincode substracc not found"
}
, response {
  status: 500
  message: "make sure the chaincode substracc has been successfully instantiated and try again: chaincode substracc not found"
}
]

**Comment by IcyLiGit** [comment]
I have solved this problem. I switch the command to python3 python-scripts/start.py --no-backup in the $SUBSTRA_SOURCE/hlf-k8s directionary. However, I still got the following issues when I run sbbac command.
(alias sbbac-wait="while ! curl substra-backend.owkin.xyz:8000 ; do sleep 2 ; done")

curl: (56) Recv failure: Connection reset by peer
